## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [9]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [10]:
a[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [17]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [21]:
np.random.random(27).reshape(3,3,3)

array([[[0.46483969, 0.93909812, 0.9000733 ],
        [0.45961618, 0.04643913, 0.18542736],
        [0.69719889, 0.16611641, 0.61341509]],

       [[0.43190654, 0.44174882, 0.04650524],
        [0.34311366, 0.75782394, 0.67579248],
        [0.14386942, 0.36243889, 0.76263059]],

       [[0.43380159, 0.5555033 , 0.98987488],
        [0.35825021, 0.61604847, 0.22701569],
        [0.50748972, 0.53843822, 0.32251966]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [22]:
np.random.random(30).mean()

0.4720564965786594

Перемножить матрицы 5x3 и 3x2

In [23]:
a = np.random.random(15).reshape(5,3)
b = np.random.random(6).reshape(3,2)
np.dot(a, b)

array([[1.06303304, 0.85944293],
       [0.90265719, 0.70845471],
       [0.62373108, 0.47671818],
       [0.78840723, 0.54750702],
       [1.04965054, 0.84639356]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [28]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [33]:
a = np.random.random(10)
print (a)
a[a == a.max()] = 0
print (a)

[0.02540229 0.54909425 0.76537143 0.41653306 0.66943428 0.40862264
 0.08234586 0.57179722 0.19058211 0.95629025]
[0.02540229 0.54909425 0.76537143 0.41653306 0.66943428 0.40862264
 0.08234586 0.57179722 0.19058211 0.        ]


Преобразовать массив из float в int

In [34]:
(np.random.random(10)*10).astype(int)

array([1, 2, 5, 2, 0, 3, 8, 7, 8, 9])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [35]:
import scipy.spatial as ss
a = (np.random.random(20)*100).astype(int).reshape(10,2)
ss.distance.cdist(a, a)

array([[ 0.        , 64.63745044, 67.35725648, 71.58910532, 84.1546196 ,
        43.829214  , 33.83784863, 49.57822102, 77.00649323, 87.20665112],
       [64.63745044,  0.        ,  7.28010989, 87.59566199, 92.13034245,
        73.02739212, 30.8058436 , 20.        , 12.80624847, 68.62215386],
       [67.35725648,  7.28010989,  0.        , 83.67795409, 87.32124598,
        71.1758386 , 33.9705755 , 19.31320792, 10.44030651, 62.24146528],
       [71.58910532, 87.59566199, 83.67795409,  0.        , 14.03566885,
        27.85677655, 74.02702209, 68.94200461, 92.76313923, 42.19004622],
       [84.1546196 , 92.13034245, 87.32124598, 14.03566885,  0.        ,
        41.        , 82.75868534, 74.88658091, 95.51963149, 35.90264614],
       [43.829214  , 73.02739212, 71.1758386 , 27.85677655, 41.        ,
         0.        , 52.        , 53.03772242, 81.39410298, 54.58937626],
       [33.83784863, 30.8058436 , 33.9705755 , 74.02702209, 82.75868534,
        52.        ,  0.        , 18.68154169

Случайно расположить p элементов в 2D массив

In [50]:
a = np.zeros((10,10))
np.put(a, np.random.choice(range(0, 100), 10, replace=False), 10)
print (a)

[[ 0.  0.  0.  0. 10.  0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10.  0. 10.  0.  0.  0.  0.  0.  0. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [93]:
a = np.array([1, 2, 3, 4, 5])
z = np.zeros(len(a)*4 - 3)
z[::4] = a[:]
print (z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [96]:
a = (np.random.random(100)*100).astype(int)
import scipy.stats as sst
sst.mode(a)

ModeResult(mode=array([4]), count=array([3]))

Найти n наибольших значений в массиве

In [101]:
n = 3
np.sort(a)[-n::]

array([97, 98, 99])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [103]:
import pandas as pd
df_food = pd.read_csv('C:\\Users\\16698655\\Documents\\en.openfoodfacts.org.products.tsv', sep='\t')

C:\Users\16698655\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [104]:
df_food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [106]:
df_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB


Сколько столбцов в наборе данных?

In [108]:
len(df_food.columns)

163

Напечатайте все названия столбцов

In [113]:
df_food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [124]:
df_food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [117]:
df_food.columns[104:105]

Index(['-glucose_100g'], dtype='object')

Как проиндексирован набор данных?

In [119]:
df_food.shape

(356027, 163)

Каково значение имени продукта в 19-м наблюдении?

In [125]:
df_food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [127]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

Как много продуктов стоят более чем $10.00?

In [185]:
chipo[chipo['item_price'].str[1:].astype('float32') > 10].count()


order_id              1130
quantity              1130
item_name             1130
choice_description    1123
item_price            1130
dtype: int64

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [189]:
chipo[['item_name', 'item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [194]:
chipo.sort_values(['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [202]:
max_price = chipo['item_price'].str[1:].astype('float32').max()
chipo[chipo['item_price'].str[1:].astype('float32') == max_price]['quantity'].sum()

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [204]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [211]:
(chipo[chipo['item_name'] == 'Canned Soda']['quantity'] > 1).sum()

20